fix artifacts verification

diff --git a/.github/workflows/android-sdk.yml b/.github/workflows/android-sdk.yml
--- a/.github/workflows/android-sdk.yml
+++ b/.github/workflows/android-sdk.yml
@@ -44,11 +44,13 @@ jobs:
             --stacktrace
 
       - name: ✅ Verify expected artifacts exist
+#        run: |
+#          echo "Checking artifacts for version ${RELEASE_VERSION}..."
+#          test -f VCL/build/outputs/aar/vcl-${RELEASE_VERSION}.aar || (echo "❌ AAR not found" && exit 1)
+#          test -f VCL/build/libs/vcl-${RELEASE_VERSION}-sources.jar || (echo "❌ Sources JAR missing" && exit 1)
+#          test -f VCL/build/libs/vcl-${RELEASE_VERSION}-javadoc.jar || (echo "❌ Javadoc JAR missing" && exit 1)
         run: |
-          echo "Checking artifacts for version ${RELEASE_VERSION}..."
-          test -f VCL/build/outputs/aar/vcl-${RELEASE_VERSION}.aar || (echo "❌ AAR not found" && exit 1)
-          test -f VCL/build/libs/vcl-${RELEASE_VERSION}-sources.jar || (echo "❌ Sources JAR missing" && exit 1)
-          test -f VCL/build/libs/vcl-${RELEASE_VERSION}-javadoc.jar || (echo "❌ Javadoc JAR missing" && exit 1)
+          ./gradlew :VCL:verifyExpectedArtifactsExist
 
       - name: 🚀 Run JReleaser full-release
         if: github.event.inputs.environment != 'dev'
